### ISSUE TITLE
Script won't be reloaded on failover

### ISSUE THREAD

**Issue by phuongnd08** [Shopify/wolverine#12]
We are using redis sentinel to do automatically failover. But when the master being changed, the script sha is not found on the new server thus won't be executed. Thoughts?

**Comment by burke** [comment]
As far as I recall, it should Just Work™, because the new master will reply with whatever error it uses to indicate the script is missing (something matching `/NOSCRIPT/`, last time I was in this codebase, anyway), and [this block](https://github.com/Shopify/wolverine/blob/master/lib/wolverine/script.rb#L35-L39) will cause it to submit the full text.

It should self-heal. Are you seeing behaviour where it doesn't self-heal?

**Comment by phuongnd08** [comment]
I think I was confused whether it was Ohm or Wolverine error (since both are using lua). I make a monkey patch for Ohm and haven't seen similar errors since then. Closing now. Thanks.
